default:
make -C /media/artur/8044fddd-e06e-4a30-af2f-7e942f0defd2/cm11/device/lge/u2-common/sgx-module/eurasiacon/build/linux2/omap4430_android KERNELDIR=/media/artur/8044fddd-e06e-4a30-af2f-7e942f0defd2/cm11/kernel/lge/omap4-common ARCH="arm" /media/artur/8044fddd-e06e-4a30-af2f-7e942f0defd2/cm11/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/bin/arm-eabi- KERNEL_CROSS_COMPILE=/media/artur/8044fddd-e06e-4a30-af2f-7e942f0defd2/cm11/prebuilt/linux-x86/toolchain/arm-eabi-4.8/bin/arm-eabi- TARGET_PRODUCT="blaze_tablet" BUILD=release TARGET_SGX=540 PLATFORM_VERSION=4.0

# /media/artur/8044fddd-e06e-4a30-af2f-7e942f0defd2/cm11/prebuilt/linux-x86/toolchain/arm-eabi-4.8/bin/arm-eabi-strip --strip-unneeded $(KERNEL_MODULES_OUT)/pvrsrvkm_sgx540_120.ko
