#!/system/bin/sh

bb=/system/xbin/busybox
$bb mount -wo remount rootfs /    
$bb mount -ro remount,rw /system;

# GPS fix
	chown system system /system/bin/glgps;
	chmod 777 /system/bin/glgps;

# disable debugging
echo 0 > /sys/module/wakelock/parameters/debug_mask;
echo 0 > /sys/module/userwakelock/parameters/debug_mask;
echo 0 > /sys/module/earlysuspend/parameters/debug_mask;
echo 0 > /sys/module/alarm/parameters/debug_mask;
echo 0 > /sys/module/alarm_dev/parameters/debug_mask;
echo 0 > /sys/module/binder/parameters/debug_mask;
echo 0 > /sys/module/lge_touch_core/parameters/debug_mask; 

#I/o sched
echo "sio" > /sys/block/mmcblk0/queue/scheduler;


iw wlan0 set power_save on;
iwconfig wlan0 power 500m;

# more rational defaults for KSM
echo 100 > /sys/kernel/mm/ksm/pages_to_scan;
echo 500 > /sys/kernel/mm/ksm/sleep_millisecs;




# wait for system being 'up'
until [ $(pgrep com.android.systemui) ] ; do
sleep 1
done

$bb echo 15000000 > /proc/sys/kernel/sched_latency_ns
$bb echo 2000000 > /proc/sys/kernel/sched_min_granularity_ns
$bb echo 3000000 > /proc/sys/kernel/sched_wakeup_granularity_ns
$bb echo 55 > /proc/sys/vm/vfs_cache_pressure
$bb echo 0 > /proc/sys/vm/dirty_writeback_centisecs
$bb echo 10240 > /proc/sys/vm/min_free_kbytes
$bb echo 8388608 > /proc/sys/vm/dirty_bytes
$bb echo 2097152 > /proc/sys/vm/dirty_background_bytes

if [ -e /dev/frandom ]; then
	chmod 644 /dev/frandom;
	mv /dev/random /dev/random.ori;
	mv /dev/urandom /dev/urandom.ori;
	ln /dev/frandom /dev/random;
	chmod 644 /dev/random;
	ln /dev/frandom /dev/urandom;
	chmod 644 /dev/urandom;
fi

sleep 1;

# block tweaks
for i in /sys/block/*/queue ; do
  echo 0 > $i/iostats
  echo 0 > $i/rotational
done

echo 2 > /sys/block/mmcblk0/queue/rq_affinity




# decrease max. realtime cpu runtime of background apps
$bb echo 91 > /dev/cpuctl/apps/bg_non_interactive/cpu.shares
$bb echo 400000 > /dev/cpuctl/apps/bg_non_interactive/cpu.rt_runtime_us

# change niceness of systemui
$bb renice -10 $($bb pgrep com.android.systemui)

# move systemui to the parent task group
$bb echo $($bb pgrep com.android.systemui) > /dev/cpuctl/tasks

# set cgroup_timer_slack for bg_non_interactive tasks
$bb echo 100000000 > /dev/cpuctl/apps/bg_non_interactive/timer_slack.min_slack_ns


